config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "tasks#index"
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit"
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
  def show
    @task = Task.find(params[:id])
  end
  def new
    @task = Task.new
  end
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to task_path, status: :see_other
  end
  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end
  def edit
    @task = Task.find(params[:id])
  end
  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  private
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container m-3">
  <h1>Edit a task</h1>
  <%= form_with model: @task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.label :completed %>
    <%= f.check_box(:completed, {}, "True", "False") %>
    <%= f.submit %>
  <% end %>
  <%= link_to "Back to index", tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="container m-3">
  <h1>My tasks</h1>
  <ul class="list-group">
    <% @tasks.each do |task| %>
      <li class="list-group-item list-group-item-action">
      <% if task.completed %>
        <i class="fa-solid fa-check text-success"></i>
      <% else %>
         <i class="fa-solid fa-xmark text-danger"></i>
      <% end %>
      <%= link_to task[:title], task_path(task[:id]), class: "card-link" %>
      &nbsp;
      <%= link_to "Delete", task_path(task[:id]), data: {turbo_method: :delete, turbo_confirm: "Delete #{task.title}?"} %>
      &nbsp;
      </li>
    <% end %>
  </ul>
<%= link_to "Create a new task", tasks_new_path, class: "btn btn-primary mt-3" %>
</div>

<%# <%= link_to new_task_path do %>
    <%# <i class="fa-solid fa-plus"></i> Add a new task %>
<%# <% end %>

app/views/tasks/new.html.erb
<div class="container m-3">
<h1 class="mb-3">Create a new task</h1>
    <%= form_with model: @task do |f| %>
  <div class="form-group mb-2">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group mb-2">
      <%= f.label :details %>
      <%= f.text_field :details, class: "form-control"  %>
  </div>
  <div class="form-group mb-2">
      <%= f.label :completed, class: "form-check-label" %>
      <%= f.check_box(:completed, {}, "True", "False") %>
  </div>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
    <br>
  <%= link_to "Back to index", tasks_path, class: "mt-3" %>
</div>

app/views/tasks/show.html.erb
<div class="container m-3">
  <h2><%= @task.title %></h2>
  <p>Details : <%= @task.details %></p>
  <p>Done : <%= @task.completed %></p>
  <%= link_to "Delete",
    task_path(@task),
    data: {turbo_method: :delete, turbo_confirm: "Delete #{@task.title}?"},
    class: "btn btn-danger mr-2"
  %>
  <%= link_to "Back to index", tasks_path, class: "btn btn-primary" %>
</div>